set shell := ['pwsh', '-c']

install-rust:
    scoop uninstall rust --global
    scoop install rust --global

do-while-install-rust:
    do \
    { \
    scoop uninstall rust --global ; \
    scoop install rust --global ; \
    Get-Command rustc ; \
    $n=$? ; \
    Write-Host "${n}" ; \
    } \
    while ( ! $n )
