_: just-choose

just-choose:
    #!/usr/bin/env sh
    choose_recipe=$(just --summary | tr ' ' '\n' | /usr/local/opt/choose-gui/bin/choose)
    echo "Choose Recipe: ${choose_recipe}"
    just "${choose_recipe}"

just-list:
    just --list

nef-playground-ios:
    nef playground --output "./ios-BowPlayground" --name "ios-bow-playground" --platform ios

open-playground-ios:
    open "./ios-BowPlayground/ios-bow-playground.app"

trash-playground-ios:
    trash "./ios-BowPlayground/ios-bow-playground.app"

nef-playground-macos:
    nef playground --output "./macos-BowPlayground" --name "macos-bow-playground" --platform macos

open-playground-macos:
    open "./macos-BowPlayground/macos-bow-playground.app"

trash-playground-macos:
    trash "./macos-BowPlayground/macos-bow-playground.app"

open-xcode-playground:
    open "./xcode-playground/Xcode-Playground.playground"

nef-playground-transform:
    nef playground --playground "./xcode-playground/Xcode-Playground.playground" --output "./Transform-BowPlayground" --name "transform-bow-playground" --platform macos

open-playground-transform:
    open "./Transform-BowPlayground/Transform-bow-playground.app"

trash-playground-transform:
    trash "./Transform-BowPlayground/Transform-bow-playground.app"

nef-help:
    nef --help