_: just-choose

just-choose:
    #!/usr/bin/env sh
    choose_recipe=$(just --summary | tr ' ' '\n' | /usr/local/opt/choose-gui/bin/choose)
    echo "Choose Recipe: ${choose_recipe}"
    just "${choose_recipe}"

just-list:
    just --list

just-evaluate:
    just --evaluate

nef-help:
    nef --help

nef-version:
    nef version

markdown_output := "./markdown-output"
xcode_playground := "./xcode-playground"
transform_bowplayground := "./Transform-BowPlayground"

# Create ios

ios_bowplayground_dir := "./ios-BowPlayground"
ios_bowplayground_name := "IosBowPlayground"

# Create ios : 1 : Create by nef
nef-playground-ios:
    nef playground --output "{{ios_bowplayground_dir}}" --name "{{ios_bowplayground_name}}" --platform ios

# Create ios : 2 : Open by Xcode
open-playground-ios:
    open "{{ios_bowplayground_dir}}/{{ios_bowplayground_name}}.app"

# Create ios : 3 : Compile by nef
compile-playground-ios:
    nef compile --project "{{ios_bowplayground_dir}}/{{ios_bowplayground_name}}.app"

# Create ios : 4 : Generate Markdown by nef
markdown-playground-ios:
    nef markdown --project "{{ios_bowplayground_dir}}/{{ios_bowplayground_name}}.app" --output "{{markdown_output}}"

# Create ios : clean PlayGround
trash-playground-ios:
    trash "{{ios_bowplayground_dir}}/{{ios_bowplayground_name}}.app"

# Create ios : clean Markdown
trash-playground-ios-markdown:
    trash "{{markdown_output}}/$(echo {{ios_bowplayground_name}} | tr [A-Z] [a-z])"

# Create macos

macos_bowplayground_dir := "./macos-BowPlayground"
macos_bowplayground_name := "MacosBowPlayground"

# Create macos : 1 : Create by nef
nef-playground-macos:
    nef playground --output "{{macos_bowplayground_dir}}" --name "{{macos_bowplayground_name}}" --platform macos

# Create macos : 2 : Open by Xcode
open-playground-macos:
    open "{{macos_bowplayground_dir}}/{{macos_bowplayground_name}}.app"

# Create macos : 3 : Compile by nef
compile-playground-macos:
    nef compile --project "{{macos_bowplayground_dir}}/{{macos_bowplayground_name}}.app"

# Create macos : 4 : Generate Markdown by nef
markdown-playground-macos:
    nef markdown --project "{{macos_bowplayground_dir}}/{{macos_bowplayground_name}}.app" --output "{{markdown_output}}"

# Create macos : Clean PlayGround
trash-playground-macos:
    trash "{{macos_bowplayground_dir}}/{{macos_bowplayground_name}}.app"

# Create macos : Clean Markdown
trash-playground-macos-markdown:
    trash "{{markdown_output}}/$(echo {{macos_bowplayground_name}} | tr [A-Z] [a-z])"

# macOS Blank

macos_blank_playground_dir := "macOS-Blank.playground"
macos_blank_bowplayground_name := "MacosBlank"

# macOS Blank : 1 : Open PlayGround by Xcode
open-xcode-playground-macOS-Blank:
    open "{{xcode_playground}}/{{macos_blank_playground_dir}}"

# macOS Blank : 2 : Transform PlayGround by nef
nef-playground-transform-macOS-Blank:
    nef playground --playground "{{xcode_playground}}/{{macos_blank_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{macos_blank_bowplayground_name}}" --platform macos

# macOS Blank : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-macOS-Blank:
    open "{{transform_bowplayground}}/{{macos_blank_bowplayground_name}}.app"

# macOS Blank : 4 : Compile Transformed PlayGround by nef
compile-transformed-playground-macOS-Blank:
    nef compile --project "{{transform_bowplayground}}/{{macos_blank_bowplayground_name}}.app"

# macOS Blank : 5 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-macOS-Blank:
    nef markdown --project "{{transform_bowplayground}}/{{macos_blank_bowplayground_name}}.app" --output "{{markdown_output}}"

# macOS Blank : Clean Transformed PlayGround
trash-transformed-playground-macOS-Blank:
    trash "{{transform_bowplayground}}/{{macos_blank_bowplayground_name}}.app"

# macOS Blank : Clean Markdown
trash-transformed-playground-macOS-Blank-markdown:
    trash "{{markdown_output}}/$(echo {{macos_blank_bowplayground_name}} | tr [A-Z] [a-z])"

# macOS Game

macos_game_playground_dir := "macOS-Game.playground"
macos_game_bowplayground_name := "MacosGame"

# macOS Game : 1 : Open PlayGround by Xcode
open-xcode-playground-macOS-Game:
    open "{{xcode_playground}}/{{macos_game_playground_dir}}"

# macOS Game : 2 : Transform PlayGround by nef
nef-playground-transform-macOS-Game:
    nef playground --playground "{{xcode_playground}}/{{macos_game_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{macos_game_bowplayground_name}}" --platform macos

# macOS Game : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-macOS-Game:
    open "{{transform_bowplayground}}/{{macos_game_bowplayground_name}}.app"

# macOS Game : 4 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-macOS-Game:
    nef markdown --project "{{transform_bowplayground}}/{{macos_game_bowplayground_name}}.app" --output "{{markdown_output}}"

# macOS Game : Clean Transformed PlayGround
trash-transformed-playground-macOS-Game:
    trash "{{transform_bowplayground}}/{{macos_game_bowplayground_name}}.app"

# macOS Game : Clean Markdown
trash-transformed-playground-macOS-Game-markdown:
    trash "{{markdown_output}}/$(echo {{macos_game_bowplayground_name}} | tr [A-Z] [a-z])"

# macOS Map

macos_map_playground_dir := "macOS-Map.playground"
macos_map_bowplayground_name := "MacosMap"

# macOS Map : 1 : Open PlayGround by Xcode
open-xcode-playground-macOS-Map:
    open "{{xcode_playground}}/{{macos_map_playground_dir}}"

# macOS Map : 2 : Transform PlayGround by nef
nef-playground-transform-macOS-Map:
    nef playground --playground "{{xcode_playground}}/{{macos_map_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{macos_map_bowplayground_name}}" --platform macos

# macOS Map : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-macOS-Map:
    open "{{transform_bowplayground}}/{{macos_map_bowplayground_name}}.app"

# macOS Map : 4 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-macOS-Map:
    nef markdown --project "{{transform_bowplayground}}/{{macos_map_bowplayground_name}}.app" --output "{{markdown_output}}"

# macOS Map : Clean Transformed PlayGround
trash-transformed-playground-macOS-Map:
    trash "{{transform_bowplayground}}/{{macos_map_bowplayground_name}}.app"

# macOS Map : Clean Markdown
trash-transformed-playground-macOS-Map-markdown:
    trash "{{markdown_output}}/$(echo {{macos_map_bowplayground_name}} | tr [A-Z] [a-z])"

# macOS Single View

macos_singleview_playground_dir := "macOS-SingleView.playground"
macos_singleview_bowplayground_name := "MacosSingleView"

# macOS Single View : 1 : Open PlayGround by Xcode
open-xcode-playground-macOS-SingleView:
    open "{{xcode_playground}}/{{macos_singleview_playground_dir}}"

# macOS Single View : 2 : Transform PlayGround by nef
nef-playground-transform-macOS-SingleView:
    nef playground --playground "{{xcode_playground}}/{{macos_singleview_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{macos_singleview_bowplayground_name}}" --platform macos

# macOS Single View : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-macOS-SingleView:
    open "{{transform_bowplayground}}/{{macos_singleview_bowplayground_name}}.app"

# macOS Single View : 4 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-macOS-SingleView:
    nef markdown --project "{{transform_bowplayground}}/{{macos_singleview_bowplayground_name}}.app" --output "{{markdown_output}}"

# macOS Single View : Clean Transformed PlayGround
trash-transformed-playground-macOS-SingleView:
    trash "{{transform_bowplayground}}/{{macos_singleview_bowplayground_name}}.app"

# macOS Single View : Clean Markdown
trash-transformed-playground-macOS-SingleView-markdown:
    trash "{{markdown_output}}/$(echo {{macos_singleview_bowplayground_name}} | tr [A-Z] [a-z])"

# iOS Blank

ios_blank_playground_dir := "iOS-Blank.playground"
ios_blank_bowplayground_name := "IosBlank"

# iOS Blank : 1 : Open PlayGround by Xcode
open-xcode-playground-iOS-Blank:
    open "{{xcode_playground}}/{{ios_blank_playground_dir}}"

# iOS Blank : 2 : Transform PlayGround by nef
nef-playground-transform-iOS-Blank:
    nef playground --playground "{{xcode_playground}}/{{ios_blank_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{ios_blank_bowplayground_name}}" --platform ios

# iOS Blank : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-iOS-Blank:
    open "{{transform_bowplayground}}/{{ios_blank_bowplayground_name}}.app"

# iOS Blank : 4 : Compile Transformed PlayGround by nef
compile-transformed-playground-iOS-Blank:
    nef compile --project "{{transform_bowplayground}}/{{ios_blank_bowplayground_name}}.app"

# iOS Blank : 5 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-iOS-Blank:
    nef markdown --project "{{transform_bowplayground}}/{{ios_blank_bowplayground_name}}.app" --output "{{markdown_output}}"

# iOS Blank : Clean Transformed PlayGround
trash-transformed-playground-iOS-Blank:
    trash "{{transform_bowplayground}}/{{ios_blank_bowplayground_name}}.app"

# iOS Blank : Clean Markdown
trash-transformed-playground-iOS-Blank-markdown:
    trash "{{markdown_output}}/$(echo {{ios_blank_bowplayground_name}} | tr [A-Z] [a-z])"

# iOS Single View

ios_singleview_playground_dir := "iOS-SingleView.playground"
ios_singleview_bowplayground_name := "IosSingleView"

# iOS Single View : 1 : Open PlayGround by Xcode
open-xcode-playground-iOS-SingleView:
    open "{{xcode_playground}}/{{ios_singleview_playground_dir}}"

# iOS Single View : 2 : Transform PlayGround by nef
nef-playground-transform-iOS-SingleView:
    nef playground --playground "{{xcode_playground}}/{{ios_singleview_playground_dir}}" --output "{{transform_bowplayground}}" --name "{{ios_singleview_bowplayground_name}}" --platform ios

# iOS Single View : 3 : Open Transformed PlayGround by Xcode
open-transformed-playground-iOS-SingleView:
    open "{{transform_bowplayground}}/{{ios_singleview_bowplayground_name}}.app"

# iOS Single View : 4 : Render Markdown for Transformed PlayGround by nef
markdown-transformed-playground-iOS-SingleView:
    nef markdown --project "{{transform_bowplayground}}/{{ios_singleview_bowplayground_name}}.app" --output "{{markdown_output}}"

# iOS Single View : Clean Transformed PlayGround
trash-transformed-playground-iOS-SingleView:
    trash "{{transform_bowplayground}}/{{ios_singleview_bowplayground_name}}.app"

# iOS Single View : Clean Markdown
trash-transformed-playground-iOS-SingleView-markdown:
    trash "{{markdown_output}}/$(echo {{ios_singleview_bowplayground_name}} | tr [A-Z] [a-z])"
